---
name: Bluesky Test

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - klaas-2026-007
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bluesky:
    name: 🦋 Post a Bluesky test update
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: myConsciousness/bluesky-post@v5
        with:
          text: |
            Bluesky test post from ${{ github.event.repository.name }}.

            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}

            Commit details:
            ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
